namespace InvisibleSP.Application.Common.Identity;

/// <summary>Contains claim-type names used by InvisibleSP identity tokens.</summary>
public static class IdentityClaimTypes
{
    /// <summary>Gets the claim type used for application permissions.</summary>
    public const string Permission = "permission";
}

/// <summary>Contains authorization policy names used by the application.</summary>
public static class IdentityPolicies
{
    /// <summary>Gets the policy name required for administrator access.</summary>
    public const string Administrator = "administrator";
}

/// <summary>Contains token-type identifiers used by the JWT implementation.</summary>
public static class JwtTokenTypes
{
    /// <summary>Gets the token type for access tokens.</summary>
    public const string Access = "access";

    /// <summary>Gets the token type for refresh tokens.</summary>
    public const string Refresh = "refresh";
}

/// <summary>Represents a generic application response with success state, optional data, and errors.</summary>
/// <typeparam name="T">The response data type.</typeparam>
/// <param name="Succeeded">Indicates whether the operation succeeded.</param>
/// <param name="Data">The operation result when successful; otherwise <see langword="null"/>.</param>
/// <param name="Errors">The errors returned by the operation.</param>
public sealed record Response<T>(bool Succeeded, T? Data, IReadOnlyCollection<string> Errors) : IResponse
{
    /// <summary>Creates a successful response containing the supplied data.</summary>
    /// <param name="data">The successful operation result.</param>
    /// <returns>A successful response.</returns>
    public static Response<T> Success(T data) => new(true, data, Array.Empty<string>());

    /// <summary>Creates a failed response containing the supplied errors.</summary>
    /// <param name="errors">The errors describing the failed operation.</param>
    /// <returns>A failed response.</returns>
    public static Response<T> Failure(IEnumerable<string> errors) => new(false, default, errors.ToArray());
}

/// <summary>Represents the access and refresh tokens issued to an authenticated user.</summary>
/// <param name="TokenType">The HTTP authorization scheme for the access token.</param>
/// <param name="AccessToken">The issued access token.</param>
/// <param name="ExpiresIn">The access-token lifetime in seconds.</param>
/// <param name="RefreshToken">The issued refresh token.</param>
public sealed record TokenResponse(
    string TokenType,
    string AccessToken,
    int ExpiresIn,
    string RefreshToken);

/// <summary>Represents the result of an identity operation that does not return data.</summary>
/// <param name="Succeeded">Indicates whether the operation succeeded.</param>
/// <param name="Errors">The errors returned by the operation.</param>
public sealed record IdentityResultResponse(bool Succeeded, IReadOnlyCollection<string> Errors) : IResponse
{
    /// <summary>Creates a successful identity result.</summary>
    /// <returns>A successful result without errors.</returns>
    public static IdentityResultResponse Success() => new(true, Array.Empty<string>());

    /// <summary>Creates a failed identity result.</summary>
    /// <param name="errors">The errors describing the failure.</param>
    /// <returns>A failed result.</returns>
    public static IdentityResultResponse Failure(IEnumerable<string> errors) => new(false, errors.ToArray());
}

/// <summary>Represents basic identity information exposed to the authenticated user.</summary>
/// <param name="Email">The user's email address.</param>
/// <param name="IsEmailConfirmed">Indicates whether the email address is confirmed.</param>
public sealed record IdentityInfoResponse(string Email, bool IsEmailConfirmed);

/// <summary>Represents the current authenticator-based two-factor configuration.</summary>
/// <param name="SharedKey">The authenticator shared key, when available.</param>
/// <param name="RecoveryCodesLeft">The number of unused recovery codes.</param>
/// <param name="RecoveryCodes">New recovery codes generated by the operation, when requested.</param>
/// <param name="IsTwoFactorEnabled">Indicates whether two-factor authentication is enabled.</param>
/// <param name="IsMachineRemembered">Indicates whether the current machine is remembered.</param>
public sealed record TwoFactorResponse(
    string? SharedKey,
    int RecoveryCodesLeft,
    IReadOnlyCollection<string>? RecoveryCodes,
    bool IsTwoFactorEnabled,
    bool IsMachineRemembered);

/// <summary>Represents the current first-time setup status of the application.</summary>
/// <param name="IsSetupRequired">Indicates whether initial setup is still required.</param>
/// <param name="IsSetupComplete">Indicates whether initial setup has completed.</param>
public sealed record SetupStatusResponse(bool IsSetupRequired, bool IsSetupComplete) : IResponse;
