<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="MudBlazor" Version="9.8.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\InvisibleSP.Application\InvisibleSP.Application.csproj" />
    <ProjectReference Include="..\InvisibleSP.Composition\InvisibleSP.Composition.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>
</Project>
